import { createToolHandler, defineToolSet } from "@fastgpt-plugin/sdk-factory";
import z from "zod";
import {
  InputType as executeCalculationInputType,
  OutputType as executeCalculationOutputType,
  tool as executeCalculationTool,
} from "./children/executeCalculation";
import {
  InputType as getServiceInfoInputType,
  OutputType as getServiceInfoOutputType,
  tool as getServiceInfoTool,
} from "./children/getServiceInfo";

const secretSchema = z.object({
  spreadapiApiKey: z.string().optional().nullable().meta({
    title: "SpreadAPI API Key",
    description:
      "可选的 SpreadAPI API Key。填写后会作为 Authorization: Bearer 发送",
    toolDescription:
      "Optional SpreadAPI API key sent as a Bearer token when calling published services.",
    isSecret: true,
  }),
  serviceUrl: z.string().url().meta({
    title: "服务 URL",
    description:
      "SpreadAPI 发布的服务 URL。支持 /d/{id} 分享地址、服务详情 URL 或 execute endpoint",
    toolDescription:
      "Published SpreadAPI service URL. Supports /d/{id} share URLs, service metadata URLs, or execute endpoints.",
    isSecret: false,
  }),
});

const spreadApiCommonInputSchema = {
  query: z.record(z.string(), z.any()).optional().default({}).meta({
    title: "查询参数",
    description: "附加到请求 URL 的 query 参数对象",
    toolDescription:
      "Optional query parameters object appended to the service request URL.",
  }),
  timeout: z.number().int().positive().optional().default(30000).meta({
    title: "超时时间",
    description: "请求超时时间，单位毫秒",
    toolDescription: "Request timeout in milliseconds.",
  }),
  serviceToken: z.string().optional().nullable().meta({
    title: "服务 Token",
    description: "SpreadAPI 服务级 token，可按 includeTokenMode 发送",
    toolDescription:
      "Optional service-level token for the published SpreadAPI service.",
  }),
};

const executeCalculationHandler = createToolHandler({
  inputSchema: z.object({
    ...spreadApiCommonInputSchema,
    method: z.enum(["POST", "GET"]).default("POST").meta({
      title: "请求方法",
      description: "调用服务时使用 POST 或 GET",
      toolDescription: "HTTP method used to call the SpreadAPI service.",
    }),
    inputs: z.record(z.string(), z.any()).optional().default({}).meta({
      title: "输入值",
      description: "传给 SpreadAPI 计算服务的 inputs 对象",
      toolDescription:
        "Input values object passed to the published spreadsheet calculation service.",
    }),
    includeTokenMode: z.enum(["none", "query", "body"]).default("none").meta({
      title: "服务 Token 发送方式",
      description: "控制 serviceToken 不发送、放入 query 或放入 body",
      toolDescription:
        "Controls whether serviceToken is omitted, sent as a query parameter, or included in the POST body.",
    }),
  }),
  outputSchema: executeCalculationOutputType,
  secretSchema: z.object({}),
  handler: async (input, ctx) => {
    const parsedInput = await executeCalculationInputType.parseAsync({
      ...input,
      ...ctx.secrets,
    });
    const output = await executeCalculationTool(parsedInput, ctx);
    return executeCalculationOutputType.parseAsync(output);
  },
});

const getServiceInfoHandler = createToolHandler({
  inputSchema: z.object({
    ...spreadApiCommonInputSchema,
    infoPath: z.string().optional().default("").meta({
      title: "信息路径",
      description:
        "服务信息接口路径。留空时读取 /api/v1/services/{id} 服务详情",
      toolDescription:
        "Path appended to serviceUrl to fetch service metadata. Leave empty to read the default service metadata endpoint.",
    }),
    includeTokenMode: z.enum(["none", "query"]).default("none").meta({
      title: "服务 Token 发送方式",
      description: "控制 serviceToken 不发送或放入 query",
      toolDescription:
        "Controls whether serviceToken is omitted or sent as a query parameter.",
    }),
  }),
  outputSchema: getServiceInfoOutputType,
  secretSchema: z.object({}),
  handler: async (input, ctx) => {
    const parsedInput = await getServiceInfoInputType.parseAsync({
      ...input,
      ...ctx.secrets,
    });
    const output = await getServiceInfoTool(parsedInput, ctx);
    return getServiceInfoOutputType.parseAsync(output);
  },
});

const toolSet = defineToolSet({
  manifest: {
    pluginId: "spreadapi",
    name: {
      en: "SpreadAPI Spreadsheet Calculation",
      "zh-CN": "SpreadAPI 表格计算",
    },
    description: {
      en: "Call published SpreadAPI Excel REST APIs to execute calculations and get service info.",
      "zh-CN":
        "调用 SpreadAPI 发布的 Excel REST API,执行表格计算并获取服务信息。",
    },
    version: "0.1.0",
    versionDescription: {
      en: "Initial version",
      "zh-CN": "Initial version",
    },
    toolDescription:
      "A SpreadAPI toolset for executing published Excel calculation services. Use the service URL generated by SpreadAPI, pass input values, and receive calculated outputs.",
    tutorialUrl: "https://spreadapi.io/docs",
    author: "FastGPT Team",
    tags: ["tools"],
  },
  secretSchema,
  children: [
    {
      id: "executeCalculation",
      name: {
        en: "Execute Calculation",
        "zh-CN": "执行表格计算",
      },
      description: {
        en: "Execute a published SpreadAPI spreadsheet calculation service",
        "zh-CN": "执行 SpreadAPI 发布的表格计算服务",
      },
      toolDescription:
        "Call a SpreadAPI service URL with input values, query parameters, and optional service token.",
      handler: executeCalculationHandler,
    },
    {
      id: "getServiceInfo",
      name: {
        en: "Get Service Info",
        "zh-CN": "获取服务信息",
      },
      description: {
        en: "Get metadata from a published SpreadAPI service",
        "zh-CN": "获取 SpreadAPI 发布服务的元信息",
      },
      toolDescription:
        "Fetch service metadata from the SpreadAPI info endpoint.",
      handler: getServiceInfoHandler,
    },
  ],
});

export default toolSet;
